name: pgo - embedded
on:
  push:
    paths: ["embedded/**"]
jobs:
  build:
    name: 'Go Build (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        working-directory: "./embedded"
        run: go get .
      - name: Build
        working-directory: "./embedded"
        run: go build ./...
  static:
    name: 'Go Static (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - name: vet
        working-directory: "./embedded"
        run: 'go vet ./...'
      - name: staticcheck
        working-directory: "./embedded"
        run: 'staticcheck ./...'
  test:
    name: 'Go Test (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install dependencies
        working-directory: "./embedded"
        run: go get .
      - name: Test
        working-directory: "./embedded"
        run: go test -v ./...
